require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'unleashpoc' do
  config = use_native_modules!
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  
  use_react_native!(:path => config["reactNativePath"])

  target 'unleashpocTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

target 'unleashpoc-tvOS' do
  # Pods for unleashpoc-tvOS

  target 'unleashpoc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
